version: 2
jobs:
  one:
    docker:
      - image: maven:3.6.3-jdk-8-slim
    steps:
      - checkout
      - run: java -version
      - run: mvn -v
      - run: mvn clean install -DskipTests
  two:
    docker:
      - image: node:10.18.1-alpine3.9
    steps:
      - checkout
      - run: node -v
      - run: npm -v
      - run: npm set progress=false
      - run: npm i
workflows:
  version: 2
  deploy:
    jobs:
      - one
      - two