version: 2
jobs:
  one:
    docker:
      - image: openjdk:8
    steps:
      - checkout
      - run: pwd
      - run: ls -lah
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: java --version
workflows:
  version: 2
  deploy:
    jobs:
      - one
      - two