version: 2
jobs:
  maven-build:
    docker:
      - image: maven:3.6.3-jdk-8-slim
    steps:
      - checkout
#      - setup_remote_docker:
#          docker_layer_caching: true
      - restore_cache:
          key: mvn-dependency-cache-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          key: mvn-dependency-cache-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - run: mvn clean install -DskipTests -Pproduction
      - run: mvn tomee:run -DskipTests -Pproduction
      - store_artifacts: # See circleci.com/docs/2.0/artifacts/ for more details.
          path: /target/vaadin-showcase-1.0-SNAPSHOT.war
          destination: app.war
  npm-build:
    docker:
      - image: node:10.18.1-alpine3.9
    steps:
      - checkout
      - restore_cache:
          key: npm-dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm set progress=false
      - run: npm i --prefer-offline
      - save_cache:
          key: npm-dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
workflows:
  version: 2
  deploy:
    jobs:
      - maven-build
      - npm-build