version: 2
jobs:
  one:
    docker:
      - image: maven:3.6.3-jdk-8-slim
    steps:
      - checkout
      - run: java -version
      - run: mvn -v
      - run: mvn clean install -DskipTests
  two:
    docker:
      - image: node:10.18.1-alpine3.9
    steps:
      - checkout
      - restore_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm set progress=false
      - run: npm i --prefer-offline
      - save_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
        paths:
          - ./node_modules
workflows:
  version: 2
  deploy:
    jobs:
      - one
      - two