version: 2
jobs:
  maven-build:
    docker:
      - image: maven:3.6.3-jdk-8-slim
    steps:
      - checkout
#      - setup_remote_docker:
#          docker_layer_caching: true
      - restore_cache:
          key: mvn-dependency-cache-{{ checksum "pom.xml" }}
      - restore_cache:
          key: npm-dependency-cache-{{ checksum "package-lock.json" }}
      - run: mvn dependency:go-offline
      - save_cache:
          key: mvn-dependency-cache-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - save_cache:
          key: npm-dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: mvn clean install -DskipTests -Pproduction
#      - run: mvn tomee:run -DskipTests -Pproduction
#      - store_test_results:
#          path: ~/test-results/cucumber/
      - store_artifacts: # See circleci.com/docs/2.0/artifacts/ for more details.
          path: target/vaadin-showcase-1.0-SNAPSHOT.war
          destination: app.war
#      - run:
#          name: Save test results
#          command: |
#            mkdir -p ~/test-results/junit/
#            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
#          when: always
#          - store_test_results:
#              path: ~/test-results
#          - store_artifacts:
#              path: ~/test-results/junit

#    npm-build:
#        docker:
#          - image: node:10.18.1-alpine3.9
#        steps:
#          - checkout
#          - restore_cache:
#          - run: npm set progress=false
#          - run: npm i --prefer-offline
#          - save_cache:
#              key: npm-dependency-cache-{{ checksum "package-lock.json" }}
#              paths:
#                - ./node_modules
workflows:
  version: 2
  deploy:
    jobs:
      - maven-build